In [3]:
import pandas as pd 
import numpy as np 

#ML
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier, DecisionTreeRegressor
from sklearn.metrics import accuracy_score
from scipy import stats
import matplotlib.pyplot as plt
import os
import random
from sklearn.metrics import r2_score
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os
import scipy.stats
import numpy as np
import pandas as pd
import scipy.stats
import gudhi as gd
import networkx as nx
import random
from tqdm import tqdm
import os

In [5]:
scipy.stats.spearmanr([1,1,1], [1,2,3], nan_policy='omit')

/var/folders/r3/27v441rd1vb2qdthw2f3whr00000gn/T/ipykernel_4341/964909580.py:1: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  scipy.stats.spearmanr([1,1,1], [1,2,3], nan_policy='omit')

SignificanceResult(statistic=nan, pvalue=nan)

In [7]:
results_dir = '../result_85stop_10%init_nodes_limited-v4/unweighted/'
network_dir = '../networks/unweighted/'

In [9]:
network_name = "email_eu_modified"
network_list = ["email_eu_modified"]

In [11]:
simple_betas = [0.02, 0.03, 0.04, 0.05]
simple_betas = [0.02,0.021,0.022,0.023,0.024,0.025,0.026,0.027,0.028,0.029,0.03,0.031,0.032,0.033,0.021, 0.03, 0.04, 0.05]
simple_betas = [0.02]
complex_thetas = [2, 3, 4, 5, 6, 7, 8, 9]
complex_probs = [-1, 0.02, 0.03, 0.04]

observable_ratio = [0.01]

In [13]:
# Load and preprocess graph
graph_path = os.path.join(network_dir, f'G_unweighted_{network_name}.graphml')
G = nx.read_graphml(graph_path)

In [15]:
for network_name in network_list:
    # Load and preprocess graph
    graph_path = os.path.join(network_dir, f'G_unweighted_{network_name}.graphml')
    G = nx.read_graphml(graph_path)

    mapping = {node: int(float(node)) for node in G.nodes()}
    G = nx.relabel_nodes(G, mapping)

    # Process simple contagion CSVs
    for obs_ratio in observable_ratio:
        for beta in simple_betas:
            csv_path = os.path.join(results_dir, f'unweighted_simple_{network_name}_beta_{beta}.csv')
            if os.path.exists(csv_path):
                print(1)

                #for test
                partial_ratio = obs_ratio

                
                sims = pd.read_csv(csv_path)
                
                
                # Remove extra columns based on expected CSV format
                order_columns = [col for col in sims.columns if str(col).isdigit() or (str(col).lstrip('-').isdigit())]
                
                #select observable nodes
                partial_n_nodes = int(partial_ratio*len(order_columns))
                seed_curr = np.random.randint(1e8)
                np.random.seed(seed_curr)
                order_columns_obs = np.random.choice(order_columns,partial_n_nodes,replace=False)
                order_columns_obs
                
                order = sims[order_columns_obs].copy(deep=True)
                order_prl = order.copy(deep=True)
                order = order.apply(lambda row: row.fillna(row.max() + 1), axis=1)

1

In [19]:
# for row_index in tqdm(range(len(order))):

#     not_nan_ind = np.where(~order_prl.iloc[row_index].isna())[0]
#     g_node_list = np.array(list(graph.nodes()))
#     sgraph = graph.subgraph(g_node_list[not_nan_ind])
#     filt = order_prl.iloc[row_index][not_nan_ind]
#     sgraph = nx.Graph(sgraph)

In [29]:
graph = G
row_index = 0
not_nan_ind = np.where(~order_prl.iloc[row_index].isna())[0]
wanted_nodes = order_prl.columns.astype(int)[not_nan_ind]
sgraph = graph.subgraph(wanted_nodes)

filt = order_prl.iloc[row_index][not_nan_ind]
# filt = pd.DataFrame(filt).loc[np.array(sgraph.nodes).astype(str)][0].values

/var/folders/r3/27v441rd1vb2qdthw2f3whr00000gn/T/ipykernel_4341/3172721415.py:7: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  filt = order_prl.iloc[row_index][not_nan_ind]

In [31]:
pd.DataFrame(filt).loc[np.array(sgraph.nodes).astype(str)]

        0
551   7.0
137   6.0
816   3.0
403  11.0
440   5.0
186   7.0
347   7.0
60    7.0
127   7.0

In [185]:
-filt

array([ -6., -17.,  -7., -12.,  -8.,  -5.,  -7., -15.])

In [187]:
np.array(sgraph.nodes)

array([423, 937,  48, 595, 916, 853, 245, 921])

In [189]:
# filt[np.array(sgraph.nodes)[0]]
pd.DataFrame(filt).loc[np.array(sgraph.nodes).astype(str)][0].values

KeyError: "None of [Index(['423', '937', '48', '595', '916', '853', '245', '921'], dtype='object')] are in the [index]"

In [165]:
filt

916     8.0
245     7.0
853     5.0
595    12.0
423     6.0
921    15.0
48      7.0
937    17.0
Name: 0, dtype: float64

In [97]:
filt[np.array(sgraph.nodes)]

/var/folders/r3/27v441rd1vb2qdthw2f3whr00000gn/T/ipykernel_3440/535811594.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  filt[np.array(sgraph.nodes)]

IndexError: positional indexers are out-of-bounds

In [75]:
order_prl

      916  245   662   853   595  423   921  48   937
0     8.0    7   NaN   5.0  12.0    6  15.0   7  17.0
1     NaN    5   NaN  11.0  11.0    7  13.0   5   5.0
2     NaN    5   NaN  15.0  20.0   12  11.0   9  14.0
3    12.0    4   NaN   7.0   9.0    4   7.0   5   8.0
4    11.0    6   NaN   9.0  16.0    7   NaN   9   9.0
..    ...  ...   ...   ...   ...  ...   ...  ..   ...
195  12.0    7   NaN  10.0  16.0    7   5.0   7   9.0
196   NaN    5   7.0   8.0   6.0    8   NaN   6   7.0
197  17.0    7   NaN  12.0  14.0    6   NaN   5   8.0
198  12.0    5   NaN   8.0  11.0    3   NaN   8   7.0
199   NaN    6  11.0  15.0  16.0    5   NaN   7   6.0

[200 rows x 9 columns]

In [55]:
graph = G
for row_index in tqdm(range(len(order))):

    not_nan_ind = np.where(~order_prl.iloc[row_index].isna())[0]
    g_node_list = np.array(list(graph.nodes()))
    sgraph = graph.subgraph(g_node_list[not_nan_ind])
    filt = order_prl.iloc[row_index][not_nan_ind]
    sgraph = nx.Graph(sgraph)
    break

  0%|                                                   | 0/200 [00:00<?, ?it/s]/var/folders/r3/27v441rd1vb2qdthw2f3whr00000gn/T/ipykernel_3332/860888267.py:7: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  filt = order_prl.iloc[row_index][not_nan_ind]
  0%|                                                   | 0/200 [00:00<?, ?it/s]

In [71]:
dict(graph.degree).values()

dict_values([69, 82, 60, 97, 108, 53, 57, 52, 79, 74, 85, 63, 67, 97, 37, 43, 74, 23, 28, 65, 169, 39, 75, 29, 62, 74, 104, 76, 81, 70, 60, 94, 62, 23, 81, 82, 36, 27, 85, 38, 36, 30, 53, 40, 14, 52, 53, 35, 78, 34, 13, 53, 108, 2, 61, 88, 66, 63, 59, 95, 91, 80, 24, 29, 11, 39, 3, 42, 72, 3, 106, 163, 24, 25, 53, 91, 53, 25, 44, 39, 158, 77, 119, 70, 41, 74, 73, 124, 38, 42, 37, 156, 21, 50, 10, 116, 122, 28, 72, 60, 68, 46, 88, 35, 127, 67, 19, 28, 75, 40, 73, 40, 38, 103, 15, 107, 56, 48, 70, 26, 23, 28, 32, 78, 93, 47, 47, 53, 30, 46, 30, 99, 25, 21, 26, 67, 27, 17, 83, 29, 44, 101, 31, 63, 48, 42, 46, 13, 27, 16, 17, 15, 87, 9, 46, 21, 21, 37, 33, 109, 23, 35, 38, 46, 30, 30, 13, 13, 81, 55, 39, 23, 121, 30, 30, 28, 30, 35, 15, 43, 59, 53, 16, 43, 104, 40, 59, 72, 29, 41, 122, 74, 84, 57, 47, 76, 41, 168, 42, 101, 18, 49, 81, 56, 14, 61, 42, 77, 50, 40, 31, 39, 16, 8, 89, 72, 35, 23, 100, 36, 36, 36, 77, 101, 27, 5, 16, 28, 17, 8, 4, 45, 60, 26, 37, 32, 20, 10, 17, 70, 46, 42, 57, 87, 49, 37, 26, 105, 30, 23, 13, 41, 37, 57, 16, 29, 20, 40, 58, 68, 54, 19, 68, 8, 48, 46, 46, 29, 47, 55, 20, 57, 35, 21, 64, 42, 62, 19, 17, 10, 33, 52, 28, 6, 61, 27, 38, 70, 27, 66, 55, 118, 83, 40, 37, 36, 21, 6, 13, 91, 28, 41, 58, 6, 23, 63, 19, 44, 63, 12, 22, 15, 12, 67, 8, 44, 51, 25, 23, 42, 42, 20, 40, 48, 60, 21, 42, 28, 57, 6, 29, 74, 43, 50, 55, 5, 22, 31, 16, 19, 53, 26, 40, 61, 63, 61, 19, 44, 40, 48, 48, 37, 29, 25, 35, 97, 34, 76, 8, 69, 71, 9, 50, 96, 77, 29, 78, 21, 12, 85, 35, 47, 56, 39, 43, 76, 32, 19, 7, 60, 60, 19, 15, 22, 8, 17, 30, 33, 32, 20, 1, 11, 3, 45, 4, 25, 4, 9, 60, 45, 37, 21, 15])

In [57]:
g_node_list

array([1467, 1591, 1513, 1568, 1562, 1524, 1771, 1428, 1600, 1523, 1525,
       1529, 1544, 1519, 1583, 1510, 1549, 1553, 1606, 1622, 1599, 1560,
       1602, 1631, 1573, 1537, 1531, 1539, 1604, 1543, 1526, 1582, 1551,
       1269, 1463, 1628, 1552, 1514, 1547, 1504, 1601, 1629, 1616, 1518,
       1691, 1545, 1580, 1569, 1520, 1742, 1430, 1453, 1563, 1618, 1434,
       1448, 1487, 1626, 1512, 1527, 1592, 1437, 1542, 1461, 1627, 1578,
       1594, 1521, 1593, 1793, 1598, 1655, 1436, 1724, 1469, 1489, 1853,
       1915, 1451, 1459, 1441, 1789, 1920, 1538, 1874, 1574, 1532, 1617,
       1779, 1522, 1774, 1825, 1903, 1791, 1778, 1857, 1678, 1449, 1716,
       1808, 1503, 1839, 1641, 1773, 1458, 1546, 1468, 1558, 1871, 1572,
       1767, 1872, 1879, 1613, 1444, 1554, 1623, 1452, 1858, 1634, 1497,
       1500, 1511, 1556, 1590, 1530, 1559, 1596, 1464, 1619, 1904, 1517,
       1557, 1460, 1499, 1541, 1555, 1533, 1840, 1612, 1465, 1579, 1426,
       1470, 1466, 1608, 1528, 1650, 1457, 1668, 1762, 1743, 1501, 1540,
       1587, 1535, 1431, 1438, 1516, 1847, 1507, 1425, 1433, 1652, 1900,
       1747, 1917, 1548, 1495, 1493, 1790, 1912, 1731, 1888, 1916, 1828,
       1805, 1863, 1597, 1848, 1919, 1581, 1435, 1498, 1603, 1842, 1770,
       1427, 1496, 1505, 1761, 1740, 1676, 1443, 1659, 1700, 1757, 1688,
       1696, 1831, 1564, 1455, 1550, 1630, 1442, 1706, 1609, 1471, 1766,
       1648, 1783, 1756, 1640, 1486, 1752, 1749, 1585, 1645, 1707, 1764,
       1644, 1834, 1772, 1698, 1712, 1739, 1661, 1657, 1710, 1586, 1639,
       1681, 1811, 1638, 1769, 1674, 1577, 1758, 1614, 1667, 1735, 1649,
       1821, 1664, 1713, 1647, 1666, 1701, 1677, 1595, 1654, 1665, 1566,
       1642, 1675, 1651, 1685, 1727, 1845, 1643, 1689, 1576, 1911, 1784,
       1866, 1671, 1439, 1899, 1673, 1680, 1732, 1765, 1905, 1813, 1683,
       1704, 1754, 1669, 1605, 1636, 1575, 1679, 1806, 1565, 1699, 1759,
       1695, 1692, 1660, 1819, 1694, 1684, 1703, 1440, 1787, 1851, 1656,
       1682, 1687, 1635, 1702, 1625, 1711, 1697, 1670, 1477, 1672, 1728,
       1462, 1922, 1803, 1902, 1826, 1921, 1633, 1480, 1894, 1836, 1854,
       1906, 1725, 1476, 1502, 1884, 1798, 1862, 1485, 1893, 1898, 1474,
       1892, 1890, 1885, 1792, 1924, 1777, 1478, 1918, 1475, 1484, 1786,
       1850, 1914, 1901, 1880, 1841, 1794, 1897, 1855, 1491, 1877, 1923,
       1482, 1490, 1775, 1835, 1570, 1887, 1785, 1479, 1886, 1804, 1875,
       1717, 1889, 1868, 1908, 1873, 1483, 1718, 1865, 1492, 1829, 1473,
       1802, 1734, 1907, 1721, 1830, 1816, 1882, 1796, 1881, 1807, 1823,
       1818, 1755, 1768, 1715, 1663, 1780, 1760, 1646, 1708, 1817, 1658,
       1861, 1624, 1876, 1913, 1883, 1870, 1446])

In [59]:
~order_prl.iloc[row_index].isna()

0       True
1       True
2       True
3       True
4       True
       ...
398     True
399    False
400     True
401    False
402     True
Name: 0, Length: 403, dtype: bool

In [43]:
np.where(~order_prl.iloc[row_index].isna())[0]

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 110, 111, 112, 113, 114, 115, 116, 117,
       118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130,
       131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143,
       144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156,
       157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169,
       170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182,
       183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195,
       196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208,
       209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221,
       222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234,
       235, 236, 237, 238, 240, 241, 242, 243, 244, 245, 246, 247, 248,
       249, 250, 251, 252, 253, 254, 255, 256, 257, 258, 259, 260, 261,
       262, 263, 264, 265, 266, 267, 268, 269, 270, 271, 272, 273, 274,
       275, 276, 277, 278, 280, 281, 282, 283, 284, 285, 286, 287, 288,
       289, 290, 291, 292, 293, 294, 295, 296, 297, 298, 299, 300, 301,
       302, 303, 304, 305, 306, 307, 308, 309, 310, 311, 312, 313, 314,
       315, 316, 317, 318, 319, 320, 321, 322, 323, 324, 325, 326, 327,
       328, 329, 330, 331, 332, 333, 334, 335, 336, 337, 338, 339, 340,
       341, 342, 343, 344, 345, 346, 347, 348, 349, 350, 351, 352, 353,
       354, 355, 356, 357, 358, 359, 360, 361, 362, 363, 364, 365, 366,
       367, 368, 369, 370, 371, 372, 373, 374, 375, 376, 377, 378, 379,
       380, 381, 382, 383, 384, 385, 386, 387, 388, 389, 390, 391, 392,
       393, 394, 395, 396, 397, 398, 399, 400, 401, 402, 403, 404, 405,
       406, 407, 408, 409, 410, 411, 412, 413, 415, 416, 417, 418, 419,
       420, 421, 422, 423, 424, 425, 426, 427, 428, 429, 430, 431, 432,
       433, 434, 435, 436, 437, 438, 439, 440, 441, 442, 443, 444, 445,
       446, 447, 448, 450, 451, 452, 453, 454, 455, 457, 458, 459, 460,
       461, 462, 464, 465, 466, 467, 468, 469, 470, 471, 472, 473, 474,
       476, 477, 478, 480, 481, 482, 483, 484, 485, 486, 487, 488, 489,
       490, 491, 492, 493, 494, 495, 496, 497, 498, 499, 500, 501, 502,
       503, 504, 505, 506, 507, 508, 509, 510, 511, 512, 513, 514, 515,
       516, 517, 518, 519, 520, 522, 523, 525, 526, 527, 528, 529, 530,
       531, 532, 533, 535, 536, 537, 538, 539, 540, 541, 542, 543, 544,
       545, 546, 547, 548, 549, 550, 551, 552, 554, 555, 556, 557, 558,
       559, 560, 562, 563, 564, 565, 566, 568, 569, 570, 571, 572, 573,
       575, 576, 577, 578, 579, 580, 581, 583, 584, 585, 586, 587, 588,
       589, 590, 591, 592, 593, 595, 596, 598, 599, 600, 601, 603, 606,
       607, 608, 609, 610, 611, 612, 613, 614, 615, 616, 617, 618, 620,
       621, 623, 624, 626, 627, 628, 629, 630, 631, 633, 636, 637, 638,
       639, 640, 641, 642, 643, 645, 646, 648, 649, 650, 651, 652, 655,
       656, 657, 658, 659, 660, 661, 664, 667, 669, 670, 671, 673, 674,
       675, 676, 678, 681, 682, 683, 684, 685, 686, 687, 688, 689, 690,
       692, 693, 694, 695, 696, 697, 698, 699, 700, 701, 702, 703, 707,
       708, 709, 713, 714, 715, 716, 718, 719, 720, 721, 722, 724, 725,
       727, 730, 731, 732, 733, 735, 736, 737, 738, 740, 742, 745, 748,
       749, 751, 752, 755, 756, 759, 760, 761, 765, 768, 769, 770, 772,
       774, 776, 777, 779, 781, 782, 783, 784, 785, 786, 787, 788, 789,
       790, 791, 792, 793, 794, 796, 797, 798, 799, 800, 801, 802, 803,
       804, 807, 809, 810, 813, 814, 816, 818, 819, 820, 821, 822, 823,
       826, 828, 830, 831, 832, 834, 835, 836, 837, 840, 841, 846, 847,
       850, 851, 852, 853, 854, 855, 858, 861, 863, 864, 865, 867, 871,
       873, 874, 877, 881, 882, 886, 887, 888, 889, 890, 891, 893, 894,
       895, 896, 898, 899, 900, 901, 902, 903, 905, 906, 907, 908, 910,
       911, 912, 913, 914, 916, 917, 920, 921, 923, 926, 928, 929, 930,
       931, 932, 933, 934, 935, 936, 937, 938, 941, 942, 943, 944, 948,
       950, 951, 952, 953, 957, 958, 959, 960, 962, 964, 965, 967, 968,
       971, 978, 979, 981, 982, 983])

In [31]:
not_nan_ind = np.where(~order_prl.iloc[row_index].isna())[0]

,0,1,2,3,4,5,6,7,8,9,...,976,977,978,979,980,981,982,983,984,985
0,7,5,5,4,6,4,5,8,5,8,...,NaN,NaN,7.0,18.0,NaN,13.0,7.0,17.0,NaN,NaN
1,6,10,4,2,4,4,8,5,8,8,...,NaN,10.0,19.0,NaN,NaN,13.0,5.0,NaN,NaN,13.0
2,9,9,9,8,6,8,8,8,9,8,...,NaN,NaN,NaN,20.0,NaN,16.0,9.0,NaN,NaN,NaN
3,5,4,6,6,3,4,5,4,3,6,...,NaN,NaN,9.0,NaN,NaN,8.0,12.0,18.0,NaN,21.0
4,7,7,4,6,3,6,5,7,9,11,...,NaN,NaN,11.0,NaN,NaN,8.0,10.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,9,5,6,3,6,6,6,11,4,9,...,NaN,NaN,11.0,NaN,NaN,8.0,7.0,NaN,14.0,NaN
196,6,3,3,6,5,4,2,8,4,6,...,NaN,7.0,10.0,NaN,NaN,9.0,14.0,15.0,NaN,NaN
197,6,8,5,6,8,5,4,8,9,10,...,NaN,NaN,NaN,NaN,NaN,18.0,13.0,NaN,NaN,NaN
198,8,4,7,6,7,5,4,5,5,8,...,NaN,NaN,10.0,NaN,19.0,19.0,13.0,14.0,NaN,19.0
199,8,0,5,1,4,5,2,3,7,5,...,NaN,NaN,NaN,NaN,NaN,0.0,10.0,NaN,12.0,NaN

In [ ]:

# Remove extra columns based on expected CSV format
order_columns = [col for col in sims.columns if str(col).isdigit() or (str(col).lstrip('-').isdigit())]
order = sims[order_columns].copy(deep=True)
order_prl = order.copy(deep=True)
order = order.apply(lambda row: row.fillna(row.max() + 1), axis=1)

for row_index in tqdm(range(len(order))):

    not_nan_ind = np.where(~order_prl.iloc[row_index].isna())[0]
    g_node_list = np.array(list(graph.nodes()))
    sgraph = graph.subgraph(g_node_list[not_nan_ind])
    filt = order_prl.iloc[row_index][not_nan_ind]

In [97]:
partial_ratio = 0.01
graph = G
for row_index in tqdm(range(len(order))):

    # Remove extra columns based on expected CSV format
    order_columns = [col for col in sims.columns if str(col).isdigit() or (str(col).lstrip('-').isdigit())]
    
    #select observable nodes
    partial_n_nodes = int(partial_ratio*len(order_columns))
    seed_curr = np.random.randint(1e8)
    np.random.seed(seed_curr)
    order_columns_obs = np.random.choice(order_columns,partial_n_nodes,replace=False)

    order = sims[order_columns_obs].copy(deep=True)
    sgraph_prl = graph.subgraph(order_columns_obs.astype(int))
    order_prl = order.copy(deep=True)



    not_nan_ind = np.where(~order_prl.iloc[row_index].isna())[0]
    g_node_list = np.array(list(sgraph_prl.nodes()))

    print("g_node_list = ",g_node_list)
    print("order_columns_obs = ",order_columns_obs)
    sgraph = graph.subgraph(g_node_list[not_nan_ind])
    filt = order_prl.iloc[row_index][not_nan_ind]
    sgraph = nx.Graph(sgraph)
    # persistent_homology = compute_persistent_homology(graph=sgraph, filtration=filt)


    # Compute PRL (Spearman correlation)
    deg_list = list(dict(graph.degree).values())
    order_curr = list(order_prl.iloc[row_index].values)

    try:
        rho, _ = scipy.stats.spearmanr(deg_list, order_curr, nan_policy='omit')
    except Exception as e:
        print(f'PRL method could not find rho for row {row_index}: {e}')
        rho = 0

    break

  0%|                                                   | 0/200 [00:00<?, ?it/s]/var/folders/r3/27v441rd1vb2qdthw2f3whr00000gn/T/ipykernel_2670/1847689951.py:26: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  filt = order_prl.iloc[row_index][not_nan_ind]
  0%|                                                   | 0/200 [00:00<?, ?it/s]

g_node_list =  [  2 130 910 719 340 277 373 725 666]
order_columns_obs =  ['2' '373' '666' '277' '910' '719' '725' '130' '340']
PRL method could not find rho for row 0: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 986 and the array at index 1 has size 9

In [85]:
np.where(~order_prl.iloc[row_index].isna())[0]

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [91]:
order_columns_obs.astype(int)

array([408,  80, 437, 572,  62,  29, 342, 660, 615])

In [99]:
list(graph.nodes())

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,
 185,
 186,
 187,
 188,
 189,
 190,
 191,
 192,
 193,
 194,
 195,
 196,
 197,
 198,
 199,
 200,
 201,
 202,
 203,
 204,
 205,
 206,
 207,
 208,
 209,
 210,
 211,
 212,
 213,
 214,
 215,
 216,
 217,
 218,
 219,
 220,
 221,
 222,
 223,
 224,
 225,
 226,
 227,
 228,
 229,
 230,
 231,
 232,
 233,
 234,
 235,
 236,
 237,
 238,
 239,
 240,
 241,
 242,
 243,
 244,
 245,
 246,
 247,
 248,
 249,
 250,
 251,
 252,
 253,
 254,
 255,
 256,
 257,
 258,
 259,
 260,
 261,
 262,
 263,
 264,
 265,
 266,
 267,
 268,
 269,
 270,
 271,
 272,
 273,
 274,
 275,
 276,
 277,
 278,
 279,
 280,
 281,
 282,
 283,
 284,
 285,
 286,
 287,
 288,
 289,
 290,
 291,
 292,
 293,
 294,
 295,
 296,
 297,
 298,
 299,
 300,
 301,
 302,
 303,
 304,
 305,
 306,
 307,
 308,
 309,
 310,
 311,
 312,
 313,
 314,
 315,
 316,
 317,
 318,
 319,
 320,
 321,
 322,
 323,
 324,
 325,
 326,
 327,
 328,
 329,
 330,
 331,
 332,
 333,
 334,
 335,
 336,
 337,
 338,
 339,
 340,
 341,
 342,
 343,
 344,
 345,
 346,
 347,
 348,
 349,
 350,
 351,
 352,
 353,
 354,
 355,
 356,
 357,
 358,
 359,
 360,
 361,
 362,
 363,
 364,
 365,
 366,
 367,
 368,
 369,
 370,
 371,
 372,
 373,
 374,
 375,
 376,
 377,
 378,
 379,
 380,
 381,
 382,
 383,
 384,
 385,
 386,
 387,
 388,
 389,
 390,
 391,
 392,
 393,
 394,
 395,
 396,
 397,
 398,
 399,
 400,
 401,
 402,
 403,
 404,
 405,
 406,
 407,
 408,
 409,
 410,
 411,
 412,
 413,
 414,
 415,
 416,
 417,
 418,
 419,
 420,
 421,
 422,
 423,
 424,
 425,
 426,
 427,
 428,
 429,
 430,
 431,
 432,
 433,
 434,
 435,
 436,
 437,
 438,
 439,
 440,
 441,
 442,
 443,
 444,
 445,
 446,
 447,
 448,
 449,
 450,
 451,
 452,
 453,
 454,
 455,
 456,
 457,
 458,
 459,
 460,
 461,
 462,
 463,
 464,
 465,
 466,
 467,
 468,
 469,
 470,
 471,
 472,
 473,
 474,
 475,
 476,
 477,
 478,
 479,
 480,
 481,
 482,
 483,
 484,
 485,
 486,
 487,
 488,
 489,
 490,
 491,
 492,
 493,
 494,
 495,
 496,
 497,
 498,
 499,
 500,
 501,
 502,
 503,
 504,
 505,
 506,
 507,
 508,
 509,
 510,
 511,
 512,
 513,
 514,
 515,
 516,
 517,
 518,
 519,
 520,
 521,
 522,
 523,
 524,
 525,
 526,
 527,
 528,
 529,
 530,
 531,
 532,
 533,
 534,
 535,
 536,
 537,
 538,
 539,
 540,
 541,
 542,
 543,
 544,
 545,
 546,
 547,
 548,
 549,
 550,
 551,
 552,
 553,
 554,
 555,
 556,
 557,
 558,
 559,
 560,
 561,
 562,
 563,
 564,
 565,
 566,
 567,
 568,
 569,
 570,
 571,
 572,
 573,
 574,
 575,
 576,
 577,
 578,
 579,
 581,
 582,
 583,
 584,
 585,
 586,
 587,
 588,
 589,
 590,
 591,
 592,
 593,
 594,
 595,
 596,
 597,
 598,
 599,
 600,
 601,
 602,
 603,
 604,
 605,
 606,
 607,
 608,
 609,
 610,
 611,
 612,
 613,
 614,
 615,
 616,
 617,
 618,
 619,
 620,
 621,
 622,
 623,
 624,
 625,
 626,
 627,
 628,
 629,
 630,
 631,
 632,
 634,
 635,
 636,
 637,
 638,
 639,
 640,
 641,
 642,
 643,
 644,
 645,
 646,
 647,
 649,
 650,
 651,
 652,
 654,
 655,
 656,
 657,
 659,
 661,
 662,
 663,
 664,
 665,
 666,
 667,
 668,
 669,
 671,
 672,
 673,
 674,
 676,
 677,
 678,
 679,
 680,
 681,
 682,
 683,
 685,
 686,
 687,
 688,
 689,
 690,
 692,
 693,
 694,
 695,
 696,
 697,
 698,
 699,
 700,
 701,
 702,
 704,
 705,
 706,
 707,
 708,
 709,
 710,
 712,
 713,
 714,
 715,
 716,
 717,
 718,
 719,
 720,
 721,
 722,
 723,
 724,
 725,
 726,
 727,
 728,
 729,
 730,
 733,
 734,
 735,
 736,
 737,
 738,
 739,
 740,
 741,
 742,
 743,
 745,
 747,
 748,
 749,
 750,
 751,
 752,
 753,
 754,
 755,
 756,
 757,
 758,
 759,
 760,
 761,
 762,
 763,
 764,
 765,
 766,
 767,
 768,
 769,
 770,
 771,
 773,
 774,
 775,
 776,
 777,
 778,
 779,
 780,
 781,
 782,
 783,
 784,
 785,
 786,
 787,
 788,
 789,
 790,
 791,
 792,
 793,
 794,
 795,
 796,
 797,
 799,
 800,
 801,
 802,
 803,
 804,
 805,
 806,
 807,
 809,
 810,
 811,
 812,
 813,
 814,
 815,
 816,
 817,
 818,
 819,
 820,
 821,
 822,
 823,
 824,
 825,
 826,
 827,
 828,
 829,
 830,
 831,
 832,
 833,
 834,
 835,
 836,
 837,
 838,
 839,
 840,
 841,
 842,
 843,
 844,
 845,
 846,
 847,
 848,
 849,
 850,
 851,
 852,
 853,
 854,
 855,
 856,
 857,
 858,
 859,
 860,
 861,
 862,
 863,
 864,
 865,
 866,
 867,
 868,
 869,
 870,
 871,
 872,
 873,
 874,
 875,
 876,
 877,
 878,
 879,
 880,
 881,
 882,
 883,
 884,
 885,
 886,
 887,
 888,
 889,
 890,
 891,
 892,
 893,
 894,
 895,
 896,
 897,
 898,
 899,
 900,
 901,
 902,
 903,
 904,
 905,
 906,
 907,
 908,
 909,
 910,
 911,
 912,
 913,
 914,
 915,
 916,
 917,
 918,
 919,
 920,
 921,
 922,
 923,
 924,
 925,
 926,
 927,
 928,
 929,
 930,
 931,
 932,
 933,
 934,
 935,
 936,
 937,
 938,
 939,
 940,
 941,
 942,
 943,
 944,
 945,
 946,
 947,
 948,
 949,
 950,
 951,
 952,
 953,
 954,
 955,
 956,
 957,
 958,
 959,
 960,
 961,
 962,
 963,
 964,
 965,
 966,
 967,
 968,
 969,
 970,
 971,
 972,
 973,
 974,
 975,
 976,
 977,
 978,
 979,
 980,
 981,
 982,
 983,
 984,
 985,
 986,
 987,
 988,
 989,
 990,
 991,
 992,
 993,
 994,
 995,
 996,
 997,
 998,
 999,
 1000,
 1001,
 1002,
 1003,
 1004]

In [101]:
order_prl.iloc[row_index].isna()

2      False
373    False
666     True
277    False
910    False
719    False
725    False
130    False
340    False
Name: 0, dtype: bool