In [1]:
import pandas as pd 
import numpy as np 

#ML
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier

In [2]:
network_list = [
    'conf','email_eu_modified','hospital','school','work'
]

In [3]:
network_name = network_list[0]
complex_c = pd.read_csv(f'../results/weighted/given_th_n=300/weighted_complex_{network_name}_EPH.csv')
simple_c = pd.read_csv(f'../results/weighted/given_betha_n=300/weighted_simple_{network_name}_EPH.csv')
np.mean(complex_c.drop(['Unnamed: 0.1',	'Unnamed: 0','EPH',	'corr'],axis=1).isna(),axis=1)
complex_c

,Unnamed: 0.1,Unnamed: 0,0,1,2,3,4,5,6,7,...,398,399,400,401,402,theta,seed,q,EPH,corr
0,0,0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,...,1.0,2.0,2.0,2.0,2.0,0.01,0,-1,1.030075,-0.320396
1,1,1,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,...,2.0,2.0,1.0,2.0,2.0,0.01,1,-1,1.043298,-0.174355
2,2,2,1.0,1.0,1.0,1.0,1.0,2.0,2.0,1.0,...,1.0,2.0,2.0,1.0,2.0,0.01,2,-1,1.027089,-0.339712
3,3,3,1.0,2.0,1.0,1.0,2.0,1.0,1.0,1.0,...,2.0,2.0,1.0,2.0,2.0,0.01,3,-1,1.032549,-0.232518
4,4,4,1.0,1.0,2.0,2.0,1.0,1.0,1.0,2.0,...,1.0,1.0,1.0,2.0,1.0,0.01,4,-1,1.026552,-0.270898
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1795,1795,1795,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.40,295,-1,2.949212,-0.738549
1796,1796,1796,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.40,296,-1,1.718638,-0.098198
1797,1797,1797,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.40,297,-1,1.828125,0.064775
1798,1798,1798,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.40,298,-1,1.831250,0.194325
1799,1799,1799,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.40,299,-1,1.612624,0.147561

In [4]:
simple_c

,Unnamed: 0.1,Unnamed: 0,0,1,2,3,4,5,6,7,...,397,398,399,400,401,402,betha,seed,EPH,corr
0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.01,0,1.000000,0.000000
1,1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.01,1,1.000000,0.000000
2,2,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.01,2,1.000000,0.000000
3,3,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.01,3,1.000000,0.000000
4,4,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.01,4,1.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2095,2095,2095,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.60,295,1.000000,0.000000
2096,2096,2096,26.0,25.0,19.0,20.0,15.0,16.0,30.0,28.0,...,24.0,26.0,9.0,NaN,19.0,NaN,0.60,296,15.199538,-0.262978
2097,2097,2097,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.60,297,2.676895,0.290281
2098,2098,2098,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.60,298,1.000000,0.000000
2099,2099,2099,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.60,299,1.946869,-0.400912

In [5]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from scipy import stats
import matplotlib.pyplot as plt
import os

def confidence_interval(accuracy, n, confidence=0.95):
    std_error = np.sqrt(accuracy * (1 - accuracy) / n)
    z_score = stats.norm.ppf((1 + confidence) / 2)
    margin_of_error = z_score * std_error
    return (accuracy - margin_of_error, accuracy + margin_of_error)

# Assume network_list is defined

for network_name in network_list:

    # Lists to store results
    betha_set = 0.01,0.1,0.2,0.3,0.4,0.5,0.6]
    accuracies_tda = []
    ci_lower_tda = []
    ci_upper_tda = []
    accuracies_prl = []
    ci_lower_prl = []
    ci_upper_prl = []

    for beta in betha_set:
        # Read data for the current network
        complex_c = pd.read_csv(f'../results/weighted/given_th_n=300/weighted_complex_{network_name}_EPH.csv')
        simple_c = pd.read_csv(f'../results/weighted/given_betha_n=300/weighted_simple_{network_name}_EPH.csv')

        # Prepare data
        complex_curr = complex_c[['EPH','corr']]
        complex_curr['complex'] = 1

        simple_c = simple_c[simple_c['betha'] == beta]
        simple_curr = simple_c[['EPH','corr']]
        simple_curr['complex'] = 0
        print('len complex =',len(complex_curr))
        print('len simple =',len(simple_curr))

        complex_curr = complex_curr.sample(len(simple_curr),random_state=13244)
        print(network_name)
        
        merged = pd.concat([simple_curr,complex_curr])
        merged = merged.sample(len(merged),random_state=1)
        print(len(merged))
        
        X_tda = merged['EPH']
        X_prl = merged['corr']
        y = merged['complex']

        # Split data
        X_tda_train, X_tda_test, y_tda_train, y_tda_test = train_test_split(X_tda, y, test_size=0.5, random_state=42)
        X_prl_train, X_prl_test, y_prl_train, y_prl_test = train_test_split(X_prl, y, test_size=0.5, random_state=42)

        # Train and evaluate models
        dt_tda = DecisionTreeClassifier(random_state=42)
        dt_prl = DecisionTreeClassifier(random_state=42)

        dt_tda.fit(X_tda_train.values.reshape(-1, 1), y_tda_train)
        dt_prl.fit(X_prl_train.values.reshape(-1, 1), y_prl_train)

        y_tda_pred = dt_tda.predict(X_tda_test.values.reshape(-1, 1))
        y_prl_pred = dt_prl.predict(X_prl_test.values.reshape(-1, 1))

        accuracy_tda = accuracy_score(y_tda_test, y_tda_pred)
        accuracy_prl = accuracy_score(y_prl_test, y_prl_pred)

        # Calculate confidence intervals
        ci_tda = confidence_interval(accuracy_tda, len(y_tda_test))
        ci_prl = confidence_interval(accuracy_prl, len(y_prl_test))

        # Store results
        accuracies_tda.append(accuracy_tda)
        ci_lower_tda.append(ci_tda[0])
        ci_upper_tda.append(ci_tda[1])
        accuracies_prl.append(accuracy_prl)
        ci_lower_prl.append(ci_prl[0])
        ci_upper_prl.append(ci_prl[1])

    # Create the plot
    plt.figure(figsize=(8, 6))

    plt.plot(betha_set, accuracies_tda, marker='o', label='EPH')
    plt.fill_between(betha_set, ci_lower_tda, ci_upper_tda, alpha=0.2)

    plt.plot(betha_set, accuracies_prl, marker='s', label='corr(order,deg)')
    plt.fill_between(betha_set, ci_lower_prl, ci_upper_prl, alpha=0.2)
    
    # Set x-axis to show only integer values
    plt.xticks(betha_set)


    plt.xlabel('Beta (β)',fontsize=15)
    plt.ylabel('Accuracy',fontsize=15)
    plt.legend(loc='lower right',fontsize=15)

    # plt.ylim(0.90,1.01)
    
    plt.xticks(fontsize=12)
    plt.yticks(fontsize=12)
    
    plt.grid(True)

    plt.tight_layout()
    
    # Save the plot
    plt.savefig(f'../results/weighted_plots/given_betha_n=300/{network_name}_accuracy_plot.pdf', format='pdf', dpi=1200, bbox_inches='tight')
    plt.close()  # Close the plot to free up memory

/var/folders/r3/27v441rd1vb2qdthw2f3whr00000gn/T/ipykernel_5041/2214810860.py:36: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  complex_curr['complex'] = 1
/var/folders/r3/27v441rd1vb2qdthw2f3whr00000gn/T/ipykernel_5041/2214810860.py:40: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  simple_curr['complex'] = 0
/var/folders/r3/27v441rd1vb2qdthw2f3whr00000gn/T/ipykernel_5041/2214810860.py:36: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  complex_curr['complex'] = 1
/var/folders/r3/27v441rd1vb2qdthw2f3whr00000gn/T/ipykernel_5041/2214810860.py:40: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  simple_curr['complex'] = 0
/var/folders/r3/27v441rd1vb2qdthw2f3whr00000gn/T/ipykernel_5041/2214810860.py:36: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  complex_curr['complex'] = 1
/var/folders/r3/27v441rd1vb2qdthw2f3whr00000gn/T/ipykernel_5041/2214810860.py:40: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  simple_curr['complex'] = 0
/var/folders/r3/27v441rd1vb2qdthw2f3whr00000gn/T/ipykernel_5041/2214810860.py:36: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  complex_curr['complex'] = 1
/var/folders/r3/27v441rd1vb2qdthw2f3whr00000gn/T/ipykernel_5041/2214810860.py:40: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  simple_curr['complex'] = 0

len complex = 1800
len simple = 300
conf
600
len complex = 1800
len simple = 300
conf
600
len complex = 1800
len simple = 300
conf
600
len complex = 1800
len simple = 300
conf
600

/var/folders/r3/27v441rd1vb2qdthw2f3whr00000gn/T/ipykernel_5041/2214810860.py:36: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  complex_curr['complex'] = 1
/var/folders/r3/27v441rd1vb2qdthw2f3whr00000gn/T/ipykernel_5041/2214810860.py:40: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  simple_curr['complex'] = 0
/var/folders/r3/27v441rd1vb2qdthw2f3whr00000gn/T/ipykernel_5041/2214810860.py:36: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  complex_curr['complex'] = 1
/var/folders/r3/27v441rd1vb2qdthw2f3whr00000gn/T/ipykernel_5041/2214810860.py:40: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  simple_curr['complex'] = 0

len complex = 1800
len simple = 300
email_eu_modified
600
len complex = 1800
len simple = 300
email_eu_modified
600

/var/folders/r3/27v441rd1vb2qdthw2f3whr00000gn/T/ipykernel_5041/2214810860.py:36: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  complex_curr['complex'] = 1
/var/folders/r3/27v441rd1vb2qdthw2f3whr00000gn/T/ipykernel_5041/2214810860.py:40: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  simple_curr['complex'] = 0
/var/folders/r3/27v441rd1vb2qdthw2f3whr00000gn/T/ipykernel_5041/2214810860.py:36: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  complex_curr['complex'] = 1
/var/folders/r3/27v441rd1vb2qdthw2f3whr00000gn/T/ipykernel_5041/2214810860.py:40: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  simple_curr['complex'] = 0
/var/folders/r3/27v441rd1vb2qdthw2f3whr00000gn/T/ipykernel_5041/2214810860.py:36: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  complex_curr['complex'] = 1
/var/folders/r3/27v441rd1vb2qdthw2f3whr00000gn/T/ipykernel_5041/2214810860.py:40: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  simple_curr['complex'] = 0
/var/folders/r3/27v441rd1vb2qdthw2f3whr00000gn/T/ipykernel_5041/2214810860.py:36: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  complex_curr['complex'] = 1
/var/folders/r3/27v441rd1vb2qdthw2f3whr00000gn/T/ipykernel_5041/2214810860.py:40: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  simple_curr['complex'] = 0
/var/folders/r3/27v441rd1vb2qdthw2f3whr00000gn/T/ipykernel_5041/2214810860.py:36: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  complex_curr['complex'] = 1
/var/folders/r3/27v441rd1vb2qdthw2f3whr00000gn/T/ipykernel_5041/2214810860.py:40: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  simple_curr['complex'] = 0
/var/folders/r3/27v441rd1vb2qdthw2f3whr00000gn/T/ipykernel_5041/2214810860.py:36: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  complex_curr['complex'] = 1
/var/folders/r3/27v441rd1vb2qdthw2f3whr00000gn/T/ipykernel_5041/2214810860.py:40: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  simple_curr['complex'] = 0

len complex = 1800
len simple = 300
email_eu_modified
600
len complex = 1800
len simple = 300
email_eu_modified
600
len complex = 1800
len simple = 300
hospital
600
len complex = 1800
len simple = 300
hospital
600
len complex = 1800
len simple = 300
hospital
600
len complex = 1800
len simple = 300
hospital
600

/var/folders/r3/27v441rd1vb2qdthw2f3whr00000gn/T/ipykernel_5041/2214810860.py:36: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  complex_curr['complex'] = 1
/var/folders/r3/27v441rd1vb2qdthw2f3whr00000gn/T/ipykernel_5041/2214810860.py:40: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  simple_curr['complex'] = 0
/var/folders/r3/27v441rd1vb2qdthw2f3whr00000gn/T/ipykernel_5041/2214810860.py:36: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  complex_curr['complex'] = 1
/var/folders/r3/27v441rd1vb2qdthw2f3whr00000gn/T/ipykernel_5041/2214810860.py:40: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  simple_curr['complex'] = 0
/var/folders/r3/27v441rd1vb2qdthw2f3whr00000gn/T/ipykernel_5041/2214810860.py:36: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  complex_curr['complex'] = 1
/var/folders/r3/27v441rd1vb2qdthw2f3whr00000gn/T/ipykernel_5041/2214810860.py:40: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  simple_curr['complex'] = 0

len complex = 1800
len simple = 300
school
600
len complex = 1800
len simple = 300
school
600
len complex = 1800
len simple = 300
school
600
len complex = 1800
len simple = 300
school
600
len complex = 1800
len simple = 300
work
600
len complex = 1800
len simple = 300
work
600
len complex = 1800
len simple = 300
work
600
len complex = 1800
len simple = 300
work
600

/var/folders/r3/27v441rd1vb2qdthw2f3whr00000gn/T/ipykernel_5041/2214810860.py:36: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  complex_curr['complex'] = 1
/var/folders/r3/27v441rd1vb2qdthw2f3whr00000gn/T/ipykernel_5041/2214810860.py:40: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  simple_curr['complex'] = 0
/var/folders/r3/27v441rd1vb2qdthw2f3whr00000gn/T/ipykernel_5041/2214810860.py:36: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  complex_curr['complex'] = 1
/var/folders/r3/27v441rd1vb2qdthw2f3whr00000gn/T/ipykernel_5041/2214810860.py:40: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  simple_curr['complex'] = 0
/var/folders/r3/27v441rd1vb2qdthw2f3whr00000gn/T/ipykernel_5041/2214810860.py:36: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  complex_curr['complex'] = 1
/var/folders/r3/27v441rd1vb2qdthw2f3whr00000gn/T/ipykernel_5041/2214810860.py:40: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  simple_curr['complex'] = 0
/var/folders/r3/27v441rd1vb2qdthw2f3whr00000gn/T/ipykernel_5041/2214810860.py:36: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  complex_curr['complex'] = 1
/var/folders/r3/27v441rd1vb2qdthw2f3whr00000gn/T/ipykernel_5041/2214810860.py:40: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  simple_curr['complex'] = 0
/var/folders/r3/27v441rd1vb2qdthw2f3whr00000gn/T/ipykernel_5041/2214810860.py:36: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  complex_curr['complex'] = 1
/var/folders/r3/27v441rd1vb2qdthw2f3whr00000gn/T/ipykernel_5041/2214810860.py:40: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  simple_curr['complex'] = 0